export const Citiesmap = {
    "cities": [
      "Casablanca",
      "Rabat",
      "Marrakech",
      "Fes",
      "Tangier",
      "Agadir",
      "Meknes",
      "Oujda",
      "Kenitra",
      "Tetouan",
      "Safi",
      "Temara",
      "Mohammedia",
      "El Jadida",
      "Nador",
      "Beni Mellal",
      "Khouribga",
      "Settat",
      "Sale",
      "Ouarzazate",
      "Al Hoceima",
      "Essaouira",
      "Taza",
      "Ifrane",
      "Larache",
      "Ksar El Kebir",
      "Guelmim",
      "Berrechid",
      "Taourirt",
      "Tiznit",
      "Errachidia",
      "Taroudant",
      "Guercif",
      "Sidi Kacem",
      "Sidi Slimane",
      "Azrou",
      "Berkane",
      "Oulad Teima",
      "Benslimane",
      "Laayoune",
      "Dakhla",
      "Chefchaouen",
      "Midelt",
      "Sidi Bennour",
      "Tinghir",
      "Tiflet",
      "Bouznika",
      "Martil",
      "Fnideq",
      "Imintanoute",
      "Zagora",
      "Tan-Tan",
      "Smara"
    ]
  }
  